name: Flutter CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1

    - name: Get dependencies
      run: flutter pub get

    - name: Build and test app
      run: flutter build apk && flutter test
